win32 {
DESTDIR = C:\run_fast
}

unix {
DESTDIR = /media/ramdisk/fastman2
}

DEFINES += CMD_DEBUG
#CONFIG += console

DEFINES -= UNICODE
DEFINES += NOCRYPT
DEFINES += WIN32_LEAN_AND_MEAN
DEFINES += _CRT_SECURE_NO_WARNINGS
DEFINES += USE_BINARIES_ZERO_H
DEFINES += DOWNLOAD_DIR_USE_USERNAME
DEFINES += LOG_FILENAME_USE_DATE

INCLUDEPATH += $$[QT_INSTALL_PREFIX]/src/3rdparty/zlib
INCLUDEPATH += $$[QT_INSTALL_PREFIX]/include/QtZlib
